name: invent
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI & responsive design
  sizer: ^3.1.3
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  web: ^1.1.1

  # Features & utilities
  cached_network_image: ^3.3.1
  connectivity_plus: ^7.0.0
  dio: ^5.4.0
  fluttertoast: ^9.0.0
  fl_chart: ^1.1.1
  flutter_slidable: ^4.0.3
  camera: ^0.11.3
  image_picker: ^1.0.4
  permission_handler: ^12.0.1
  speech_to_text: ^7.3.0
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.5
  path: ^1.8.0

  # Security & scanning
  mobile_scanner: ^5.2.1
  flutter_secure_storage: ^9.2.2

  # Localization
  intl: ^0.19.0

  # Hive 
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/logo.png
